version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 123456
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
